import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const apiSlice = createApi({
    reducerPath: 'api', // key inside Redux store
    baseQuery: fetchBaseQuery({ baseUrl: 'https://your-api-url.com' }),
    endpoints: (builder) => ({
        loginUser: builder.mutation<{ token: string }, { username: string; password: string }>({
            query: (credentials) => ({
                url: '/login',
                method: 'POST',
                body: credentials,
            }),
        }),
        getUserConfig: builder.query<{ config: any[] }, void>({
            query: () => ({
                url: '/config',
                method: 'GET',
            }),
        }),
    }),
});

// Export hooks automatically generated by RTK Query
export const { useLoginUserMutation, useGetUserConfigQuery } = apiSlice;
